name: arts_claims_app
description: A Flutter application for ARTS Claims management.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png" 
  remove_alpha_ios: true 

flutter:
  uses-material-design: true

  assets:
    - assets/background_1.png
    - assets/background_building.png
    - assets/background.png
    - assets/claimIcon.png
    - assets/logoARTSWhite.svg
    - assets/logoWhite.png
    - assets/logoBlue.png
    - assets/iconLeft.png
    - assets/iconRight.png

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_24pt-SemiBoldItalic.ttf
          weight: 600     
          style: italic    
        - asset: fonts/Inter_24pt-SemiBold.ttf
          weight: 600

  
  # You can add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf